apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-config
  namespace: archlens
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "archlens.io"
      data_dir = "/run/spire/data"
      log_level = "INFO"
      ca_ttl = "24h"
      default_svid_ttl = "1h"

      ca_subject {
        country = ["US"]
        organization = ["ArchLens"]
        common_name = "ArchLens mTLS CA"
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      KeyManager "memory" {
        plugin_data {}
      }

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "archlens" = {
              service_account_allow_list = ["archlens:spire-agent"]
            }
          }
        }
      }
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: archlens
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.9.0
          args: ["-config", "/run/spire/config/server.conf"]
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: /run/spire/config
            - name: data
              mountPath: /run/spire/data
      volumes:
        - name: config
          configMap:
            name: spire-server-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: archlens
spec:
  selector:
    app: spire-server
  ports:
    - port: 8081
      targetPort: 8081
